# This parameter was added for the migration from "flutter_gen" that was deprecated.
# See the Flutter documentation for more information: "https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source".
synthetic-package: false
arb-dir: lib/l10n
template-arb-file: l10n_en.arb
output-localization-file: l10n_localizations.dart