name: midlet_store
description: "MIDlet Store is a free and open-source Android platform dedicated to Java J2ME games."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.3

dependencies:
  archive: ^4.0.2
  audioplayers: ^6.2.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hive: ^4.0.0-dev.2
  http: ^1.2.1
  hugeicons: ^0.0.7
  image: ^4.2.0
  intl: ^0.19.0
  isar_flutter_libs: ^4.0.0-dev.13
  package_info_plus: ^8.2.1
  path_provider: ^2.1.4
  provider: ^6.1.2
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/badges/
    - assets/brands/
    - assets/flags/
    - assets/publishers/
  generate: true
  uses-material-design: true