name: Feature Request
description: Suggest a new feature or improvement for the project.
title: ✨ Hey, I thought of something cool.
labels: ["✨ Feature"]
assignees:
  - KidGbzin
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a feature request. We appreciate your input and will work on improving the project as much as possible. ❤️

  - type: checkboxes
    id: confirmations
    attributes:
      label: Before submitting, please confirm the following to ensure your request is relevant and up-to-date.
      options:
        - label: "I am using the latest version of the project."
          required: true
        - label: "I have searched the issue tracker and this feature has not been requested yet."
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like to see?
      description: |
        Provide a clear and detailed explanation of the feature request:
        - What specific functionality would you like to see?
        - Why do you think this feature would improve the project?
        - How do you envision this feature working?
      placeholder: Describe the feature request here.
    validations:
      required: true